# Generated by Django 5.1.6 on 2025-02-06 17:23

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت '),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.localtime, verbose_name='زمان انتشار '),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان اپدیت '),
        ),
    ]
