# Generated by Django 5.1.6 on 2025-02-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_parent_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['published'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', '-position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
